/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/kqlBookTheme.ts
 * Command: astryx theme build src/styles/kqlBookTheme.ts
 * Generated: 2026-07-28T04:30:25.155Z
 */

/// <reference path="./kql-book.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const kqlBookTheme: DefinedTheme;
