/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/kqlBookTheme.ts
 * Command: astryx theme build src/styles/kqlBookTheme.ts
 * Generated: 2026-07-28T04:30:25.154Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
