import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 760px)";
const splitCompact = "@media (max-width: 1125px)";
const splitWide = "@media (min-width: 1500px)";
const shortViewport = "@media (max-height: 420px)";
const reducedMotion = "@media (prefers-reduced-motion: reduce)";

export const styles = stylex.create({
	appShell: {
		backgroundColor: "#ffffff",
		minHeight: "100dvh",
	},
	navDesktop: {
		alignItems: "center",
		display: "flex",
		gap: 2,
		[mobile]: {
			display: "none",
		},
	},
	navMobile: {
		display: "none",
		[mobile]: {
			display: "block",
		},
	},
	authCluster: {
		alignItems: "center",
		display: "flex",
		gap: 8,
	},
	loginButton: {
		backgroundColor: "#0d0d0d",
		color: "#ffffff",
	},
	searchPage: {
		backgroundColor: "#ffffff",
		marginInline: "auto",
		maxWidth: 940,
		minHeight: "calc(100dvh - 48px)",
		paddingBlock: 48,
		paddingInline: 24,
		width: "100%",
		[mobile]: {
			paddingBlock: 28,
			paddingInline: 16,
		},
	},
	searchResultsPage: {
		paddingBlockStart: 38,
	},
	searchWorkspace: {
		backgroundColor: "#ffffff",
		display: "flex",
		height: "calc(100dvh - 48px)",
		minHeight: 0,
		overflow: "hidden",
		width: "100%",
	},
	searchWorkspaceInspecting: {
		backgroundColor: "var(--color-background-surface)",
	},
	queryListPane: {
		backgroundColor: "#ffffff",
		flexShrink: 0,
		height: "100%",
		minWidth: 0,
		overflowX: "hidden",
		overflowY: "auto",
		overscrollBehaviorY: "contain",
		position: "relative",
		scrollbarWidth: "none",
		transitionDuration: "300ms",
		transitionProperty: "width, background-color",
		transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
		width: "100%",
		[reducedMotion]: {
			transitionDuration: "1ms",
		},
	},
	queryListPaneInspecting: {
		backgroundColor: "var(--color-background-body)",
		width: "32vw",
		[splitCompact]: {
			width: 360,
		},
		[splitWide]: {
			width: 480,
		},
		[mobile]: {
			width: 0,
		},
	},
	queryListContent: {
		marginInline: "auto",
		minHeight: "100%",
		transitionDuration: "300ms",
		transitionProperty: "padding-block-start, padding-block-end, width",
		transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
		width: "min(988px, 100%)",
		[reducedMotion]: {
			transitionDuration: "1ms",
		},
	},
	queryListContentLanding: {
		paddingBlockStart: "calc(100dvh - 214px)",
	},
	queryListContentResults: {
		paddingBlock: 38,
	},
	resultsChrome: {
		marginInline: "auto",
		paddingInline: 24,
		width: "min(940px, 100%)",
		[mobile]: {
			paddingInline: 16,
		},
	},
	resultsChromeHidden: {
		pointerEvents: "none",
		visibility: "hidden",
	},
	queryCollection: {
		marginInline: "auto",
		minHeight: "calc(100dvh - 48px)",
		paddingInline: 24,
		transitionDuration: "300ms",
		transitionProperty: "padding-inline",
		transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
		width: "100%",
		[mobile]: {
			paddingInline: 16,
		},
		[reducedMotion]: {
			transitionDuration: "1ms",
		},
	},
	queryCollectionInspecting: {
		minHeight: "100%",
		paddingInline: 0,
	},
	searchLanding: {
		backgroundColor: "#ffffff",
		height: "calc(100dvh - 48px)",
		minHeight: 0,
		overflowX: "hidden",
		overflowY: "auto",
		overscrollBehaviorY: "contain",
		paddingBlockStart: "calc(100dvh - 214px)",
		position: "relative",
		scrollbarWidth: "none",
		width: "100%",
	},
	landingTopFade: {
		backgroundImage:
			"linear-gradient(to bottom, #ffffff 0%, rgba(255, 255, 255, 0.92) 42%, rgba(255, 255, 255, 0) 100%)",
		height: 56,
		insetBlockStart: 52,
		insetInlineEnd: 0,
		insetInlineStart: 0,
		pointerEvents: "none",
		position: "fixed",
		zIndex: 3,
	},
	landingComposer: {
		insetInlineStart: "50%",
		insetBlockStart: "calc(50% - 60px)",
		paddingInline: 20,
		position: "absolute",
		transform: "translate(-50%, -50%)",
		willChange: "opacity, transform",
		width: "min(760px, 100%)",
		zIndex: 2,
		[mobile]: {
			insetBlockStart: "calc(50% - 52px)",
			paddingInline: 16,
		},
	},
	landingComposerSurface: {
		justifyContent: "space-between",
		minHeight: 100,
		[mobile]: {
			minHeight: 96,
		},
	},
	searchComposer: {
		marginInline: "auto",
		maxWidth: 720,
		width: "100%",
	},
	searchTitle: {
		color: "var(--color-text-primary)",
		fontSize: 28,
		fontWeight: 600,
		letterSpacing: "-0.025em",
		lineHeight: 1.2,
		marginBlockEnd: 28,
		marginBlockStart: 0,
		marginInline: 0,
		textAlign: "center",
		[mobile]: {
			fontSize: 24,
			marginBlockEnd: 22,
		},
	},
	searchTitleCompact: {
		fontSize: 20,
		marginBlockEnd: 16,
		textAlign: "start",
	},
	searchTitleLink: {
		color: "inherit",
		textDecoration: "none",
		":focus-visible": {
			outlineColor: "var(--color-text-blue)",
			outlineOffset: 3,
			outlineStyle: "solid",
			outlineWidth: 2,
		},
	},
	searchedComposer: {
		marginBlockEnd: 28,
	},
	popularPreview: {
		marginInline: "auto",
		minHeight: "calc(100dvh - 48px)",
		paddingInline: 24,
		width: "min(988px, 100%)",
		[mobile]: {
			paddingInline: 16,
		},
		[shortViewport]: {
			display: "none",
		},
	},
	popularFeedStatus: {
		alignItems: "center",
		color: "var(--color-text-secondary)",
		display: "flex",
		fontSize: 13,
		gap: 8,
		justifyContent: "center",
		minHeight: 56,
		paddingBlock: 8,
	},
	searchPageSelected: {
		height: "calc(100dvh - 48px)",
		marginInline: 0,
		maxWidth: "none",
		minHeight: 0,
		overflow: "hidden",
		padding: 0,
	},
	eyebrow: {
		color: "var(--color-text-secondary)",
		fontSize: 12,
		fontWeight: 600,
		letterSpacing: "0.08em",
		marginBlockEnd: 10,
		textTransform: "uppercase",
	},
	statusLine: {
		alignItems: "center",
		borderBottomColor: "var(--color-border)",
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		color: "var(--color-text-secondary)",
		display: "flex",
		fontSize: 12,
		justifyContent: "space-between",
		minHeight: 40,
		paddingBlock: 8,
	},
	statusStrong: {
		color: "var(--color-text-primary)",
		fontWeight: 600,
	},
	resultList: {
		backgroundColor: "var(--color-background-surface)",
		borderColor: "var(--color-border)",
		borderRadius: "var(--radius-container)",
		borderStyle: "solid",
		borderWidth: 1,
		overflow: "hidden",
	},
	resultListInspector: {
		borderInlineWidth: 0,
		borderRadius: 0,
	},
	resultRow: {
		appearance: "none",
		backgroundColor: {
			default: "transparent",
			":hover": "var(--color-background-muted)",
		},
		borderBlockEndColor: "var(--color-border)",
		borderBlockEndStyle: "solid",
		borderBlockEndWidth: 1,
		borderInline: 0,
		borderBlockStart: 0,
		color: "inherit",
		cursor: "pointer",
		display: "block",
		paddingBlock: 16,
		paddingInline: 18,
		textAlign: "start",
		textDecoration: "none",
		width: "100%",
		":focus-visible": {
			outlineColor: "var(--color-text-blue)",
			outlineOffset: -3,
			outlineStyle: "solid",
			outlineWidth: 2,
		},
		":last-child": {
			borderBlockEndWidth: 0,
		},
	},
	resultRowSelected: {
		backgroundColor: {
			default: "var(--color-overlay-pressed)",
			":hover": "var(--color-overlay-pressed)",
		},
		boxShadow: "inset 3px 0 0 var(--color-accent)",
	},
	resultTopline: {
		alignItems: "start",
		display: "flex",
		gap: 14,
		justifyContent: "space-between",
	},
	resultTitle: {
		color: "var(--color-text-primary)",
		fontSize: 15,
		fontWeight: 600,
		letterSpacing: "-0.01em",
		lineHeight: 1.35,
		margin: 0,
	},
	resultScore: {
		color: "var(--color-text-secondary)",
		flexShrink: 0,
		fontFamily: "var(--font-family-code)",
		fontSize: 11,
	},
	resultSnippet: {
		color: "var(--color-text-secondary)",
		display: "-webkit-box",
		fontSize: 13,
		lineHeight: 1.5,
		marginBlock: "7px 10px",
		overflow: "hidden",
		WebkitBoxOrient: "vertical",
		WebkitLineClamp: 2,
	},
	metadataLine: {
		alignItems: "center",
		color: "var(--color-text-secondary)",
		display: "flex",
		flexWrap: "wrap",
		fontSize: 12,
		gap: 7,
	},
	metaSeparator: {
		color: "var(--color-border-emphasized)",
	},
	inspector: {
		backgroundColor: "var(--color-background-surface)",
		flexShrink: 0,
		height: "100%",
		minWidth: 0,
		opacity: 0,
		overflowY: "auto",
		pointerEvents: "none",
		position: "relative",
		transform: "translateX(48px)",
		transitionDuration: "300ms",
		transitionProperty: "width, opacity, transform",
		transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
		width: 0,
		willChange: "width, opacity, transform",
		[mobile]: {
			transform: "translateX(32px)",
		},
		[reducedMotion]: {
			transitionDuration: "1ms",
		},
	},
	inspectorOpen: {
		borderInlineStartColor: "var(--color-border)",
		borderInlineStartStyle: "solid",
		borderInlineStartWidth: 1,
		opacity: 1,
		pointerEvents: "auto",
		transform: "translateX(0)",
		width: "68vw",
		[splitCompact]: {
			width: "calc(100% - 360px)",
		},
		[splitWide]: {
			width: "calc(100% - 480px)",
		},
		[mobile]: {
			borderInlineStartWidth: 0,
			width: "100%",
		},
	},
	inspectorInner: {
		marginInline: "auto",
		maxWidth: 920,
		paddingBlock: 26,
		paddingInline: 30,
		[mobile]: {
			paddingBlock: 18,
			paddingInline: 16,
		},
	},
	inspectorHeader: {
		alignItems: "start",
		borderBottomColor: "var(--color-border)",
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "flex",
		gap: 16,
		justifyContent: "space-between",
		marginBlockEnd: 22,
		paddingBlockEnd: 18,
		[mobile]: {
			alignItems: "stretch",
			flexDirection: "column",
		},
	},
	inspectorTitle: {
		fontSize: 22,
		fontWeight: 600,
		letterSpacing: "-0.025em",
		lineHeight: 1.3,
		marginBlock: "8px 7px",
	},
	inspectorActions: {
		alignItems: "center",
		display: "flex",
		flexShrink: 0,
		gap: 6,
	},
	inspectorHeaderActions: {
		[mobile]: {
			width: "100%",
		},
	},
	githubOrigin: {
		alignItems: "center",
		display: "flex",
		flex: 1,
		minWidth: 0,
	},
	githubRepositoryLink: {
		alignItems: "center",
		backgroundColor: {
			default: "var(--color-background-surface)",
			":hover": "var(--color-background-muted)",
		},
		borderColor: "var(--color-border)",
		borderRadius: 7,
		borderStyle: "solid",
		borderWidth: 1,
		color: "var(--color-text-primary)",
		display: "inline-flex",
		fontSize: 12,
		fontWeight: 500,
		gap: 7,
		height: 30,
		maxWidth: 320,
		minWidth: 0,
		overflow: "hidden",
		paddingInlineStart: 9,
		textDecoration: "none",
	},
	githubRepositoryName: {
		flex: 1,
		minWidth: 0,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	githubStarCount: {
		borderInlineStartColor: "var(--color-border)",
		borderInlineStartStyle: "solid",
		borderInlineStartWidth: 1,
		color: "var(--color-text-secondary)",
		display: "inline-grid",
		fontSize: 11,
		fontVariantNumeric: "tabular-nums",
		fontWeight: 500,
		height: "100%",
		minWidth: 38,
		paddingInline: 7,
		placeItems: "center",
	},
	desktopClose: {
		display: "block",
	},
	mobileClose: {
		display: "none",
		[mobile]: {
			display: "block",
		},
	},
	querySection: {
		marginBlockEnd: 26,
	},
	sectionHeading: {
		color: "var(--color-text-primary)",
		fontSize: 13,
		fontWeight: 650,
		letterSpacing: "0.01em",
		marginBlock: "0 10px",
	},
	explanation: {
		color: "var(--color-text-primary)",
		fontSize: 14,
		lineHeight: 1.65,
		margin: 0,
		maxWidth: "74ch",
	},
	tableSummary: {
		alignItems: "baseline",
		display: "flex",
		gap: 8,
	},
	detailLabel: {
		color: "var(--color-text-secondary)",
		fontSize: 11,
		fontWeight: 600,
		letterSpacing: "0.06em",
		marginBlockEnd: 5,
		textTransform: "uppercase",
	},
	detailValue: {
		color: "var(--color-text-primary)",
		fontSize: 13,
		lineHeight: 1.5,
		margin: 0,
	},
	tagList: {
		display: "flex",
		flexWrap: "wrap",
		gap: 6,
	},
	aiNotice: {
		marginBlockEnd: 18,
	},
	challengeBox: {
		alignItems: "start",
		backgroundColor: "var(--color-background-surface)",
		borderColor: "var(--color-border)",
		borderRadius: "var(--radius-container)",
		borderStyle: "solid",
		borderWidth: 1,
		display: "grid",
		gap: 14,
		marginBlock: 16,
		padding: 18,
	},
	challengeTitle: {
		color: "var(--color-text-primary)",
		fontSize: 14,
		fontWeight: 600,
		margin: 0,
	},
	challengeDescription: {
		color: "var(--color-text-secondary)",
		fontSize: 13,
		lineHeight: 1.5,
		marginBlock: "4px 0 0",
	},
	emptyWrap: {
		backgroundColor: "var(--color-background-surface)",
		borderColor: "var(--color-border)",
		borderRadius: "var(--radius-container)",
		borderStyle: "solid",
		borderWidth: 1,
		marginBlockStart: 16,
		padding: 32,
	},
	collectionPage: {
		marginInline: "auto",
		maxWidth: 1040,
		minHeight: "calc(100dvh - 48px)",
		paddingBlock: 44,
		paddingInline: 24,
		width: "100%",
		[mobile]: {
			paddingBlock: 28,
			paddingInline: 16,
		},
	},
	collectionHeader: {
		alignItems: "end",
		display: "flex",
		gap: 20,
		justifyContent: "space-between",
		marginBlockEnd: 24,
		[mobile]: {
			alignItems: "start",
			flexDirection: "column",
		},
	},
	collectionTitle: {
		fontSize: 26,
		fontWeight: 600,
		letterSpacing: "-0.03em",
		marginBlock: "0 6px",
	},
	collectionDescription: {
		color: "var(--color-text-secondary)",
		fontSize: 14,
		lineHeight: 1.55,
		margin: 0,
		maxWidth: 620,
	},
	panel: {
		backgroundColor: "var(--color-background-surface)",
		borderColor: "var(--color-border)",
		borderRadius: "var(--radius-container)",
		borderStyle: "solid",
		borderWidth: 1,
		overflow: "hidden",
	},
	panelHeader: {
		alignItems: "center",
		borderBottomColor: "var(--color-border)",
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "flex",
		justifyContent: "space-between",
		paddingBlock: 12,
		paddingInline: 16,
	},
	panelTitle: {
		fontSize: 13,
		fontWeight: 600,
		margin: 0,
	},
	historyRow: {
		alignItems: "start",
		borderBottomColor: "var(--color-border)",
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "grid",
		gap: 16,
		gridTemplateColumns: "minmax(0, 1fr) auto",
		paddingBlock: 14,
		paddingInline: 16,
		":last-child": {
			borderBottomWidth: 0,
		},
	},
	historyQuery: {
		fontSize: 14,
		fontWeight: 550,
		marginBlock: "0 5px",
	},
	historyMeta: {
		color: "var(--color-text-secondary)",
		fontSize: 12,
		margin: 0,
	},
	formPage: {
		marginInline: "auto",
		maxWidth: 820,
		minHeight: "calc(100dvh - 48px)",
		paddingBlock: 44,
		paddingInline: 24,
		width: "100%",
		[mobile]: {
			paddingBlock: 28,
			paddingInline: 16,
		},
	},
	formCard: {
		backgroundColor: "var(--color-background-surface)",
		borderColor: "var(--color-border)",
		borderRadius: "var(--radius-container)",
		borderStyle: "solid",
		borderWidth: 1,
		marginBlockStart: 22,
		padding: 24,
		[mobile]: {
			padding: 16,
		},
	},
	formGrid: {
		display: "grid",
		gap: 18,
	},
	visibilityRow: {
		alignItems: "center",
		borderBottomColor: "var(--color-border)",
		borderBottomStyle: "solid",
		borderBottomWidth: 1,
		display: "grid",
		gap: 16,
		gridTemplateColumns: "minmax(0, 1fr) minmax(220px, 260px)",
		paddingBlockEnd: 18,
		[mobile]: {
			gridTemplateColumns: "minmax(0, 1fr)",
		},
	},
	visibilityLabel: {
		color: "var(--color-text-primary)",
		fontSize: 14,
		fontWeight: 600,
	},
	visibilityDescription: {
		color: "var(--color-text-secondary)",
		fontSize: 12,
		lineHeight: 1.5,
		marginBlock: "4px 0",
	},
	aiProcessingDisclosure: {
		color: "var(--color-text-secondary)",
		fontSize: 12,
		lineHeight: 1.5,
		margin: 0,
	},
	formActions: {
		alignItems: "center",
		borderTopColor: "var(--color-border)",
		borderTopStyle: "solid",
		borderTopWidth: 1,
		display: "flex",
		gap: 10,
		justifyContent: "flex-end",
		marginBlockStart: 4,
		paddingBlockStart: 18,
		[mobile]: {
			alignItems: "stretch",
			flexDirection: "column-reverse",
		},
	},
	publicPage: {
		marginInline: "auto",
		maxWidth: 980,
		minHeight: "calc(100dvh - 48px)",
		paddingBlock: 42,
		paddingInline: 24,
		width: "100%",
		[mobile]: {
			paddingBlock: 24,
			paddingInline: 16,
		},
	},
	publicHeader: {
		alignItems: "start",
		display: "flex",
		gap: 20,
		justifyContent: "space-between",
		marginBlockEnd: 24,
		[mobile]: {
			flexDirection: "column",
		},
	},
	breadcrumb: {
		color: "var(--color-text-secondary)",
		fontSize: 12,
		marginBlockEnd: 10,
	},
	visuallyHidden: {
		clip: "rect(0 0 0 0)",
		clipPath: "inset(50%)",
		height: 1,
		overflow: "hidden",
		position: "absolute",
		whiteSpace: "nowrap",
		width: 1,
	},
});
