import { describe, expect, it, vi } from "vitest";

import { GenerationGuard } from "../../../../lib/ai/abuse-control";
import type { SearchDependencies } from "../../../../lib/search/ports";
import { SearchService } from "../../../../lib/search/service";
import type { SearchResult } from "../../../../lib/search/types";

import { handleGenerationRequest } from "./handler";

function result(): SearchResult {
	return {
		queryId: "query-1",
		versionId: "version-1",
		title: "Failed sign-ins",
		snippet: "SigninLogs | where ResultType != 0",
		dialect: "sentinel",
		tables: ["SigninLogs"],
		starCount: 0,
		sourceRepository: null,
		sourceRepositoryUrl: null,
		matchType: "lexical",
		score: 0.9,
		provenance: null,
		visibility: "public",
	};
}

function service(lexicalResults: SearchResult[]): SearchService {
	const dependencies: SearchDependencies = {
		lexical: {
			searchLexical: vi.fn().mockResolvedValue(lexicalResults),
		},
		authorization: {
			getAuthorizedByIds: vi.fn().mockResolvedValue([]),
		},
		intent: {
			extractIntent: vi.fn().mockResolvedValue({
				normalizedQuery: "failed sign-ins",
				concepts: [],
				dialect: "sentinel",
				dialectConfidence: 0.95,
				tables: ["SigninLogs"],
				operators: [],
				tags: [],
			}),
		},
		embedding: {
			embed: vi.fn().mockResolvedValue([0.1]),
		},
		semantic: {
			searchSemantic: vi.fn().mockResolvedValue([]),
		},
	};
	return new SearchService(dependencies);
}

function request(): Request {
	return new Request("https://example.com/api/ai/generate", {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			"cf-connecting-ip": "192.0.2.1",
			"x-kql-device-id": "device-1",
		},
		body: JSON.stringify({
			q: "failed sign-ins",
			dialect: "sentinel",
		}),
	});
}

function guard(): GenerationGuard {
	return new GenerationGuard({
		rateLimiter: {
			limit: vi.fn().mockResolvedValue({ success: true }),
		},
	});
}

describe("POST /api/ai/generate handler", () => {
	it("does not generate when lexical retrieval is adequate", async () => {
		const generator = { generateQuery: vi.fn() };
		const response = await handleGenerationRequest(request(), {
			searchService: service([result()]),
			generator,
			guard: guard(),
			resolveViewer: vi.fn().mockResolvedValue({ userId: null }),
		});

		expect(response.status).toBe(409);
		expect(generator.generateQuery).not.toHaveBeenCalled();
		await expect(response.json()).resolves.toMatchObject({
			error: { code: "retrieval_sufficient" },
		});
	});

	it("generates only after lexical and semantic retrieval are inadequate", async () => {
		const generated = {
			aiGenerated: true as const,
			title: "Failed sign-ins",
			kql: "SigninLogs | where ResultType != 0",
			explanation: "Finds failed sign-ins.",
			dialect: "sentinel" as const,
			tables: ["SigninLogs"],
			assumptions: [],
			supportingQueryIds: [],
			model: "deepseek/deepseek-v4-flash" as const,
			warning:
				"This query was generated by AI and was not executed or verified." as const,
		};
		const generator = {
			generateQuery: vi.fn().mockResolvedValue(generated),
		};
		const response = await handleGenerationRequest(request(), {
			searchService: service([]),
			generator,
			guard: guard(),
			resolveViewer: vi.fn().mockResolvedValue({ userId: null }),
		});

		expect(response.status).toBe(201);
		expect(generator.generateQuery).toHaveBeenCalledOnce();
		await expect(response.json()).resolves.toMatchObject({
			data: {
				generated: {
					aiGenerated: true,
					model: "deepseek/deepseek-v4-flash",
				},
				retrieval: {
					adequacy: { adequate: false },
				},
			},
		});
	});
});
