import type {
	KqlDialect,
	SearchRequest,
	SearchResult,
	SearchViewer,
} from "../search/types";

export const DEEPSEEK_MODEL = "deepseek-v4-flash";
export const DEEPSEEK_BASE_URL = "https://api.deepseek.com";
export const WORKERS_AI_EMBEDDING_MODEL = "@cf/baai/bge-m3";
export const EMBEDDING_DIMENSIONS = 1_024;

export type DeepSeekModel = typeof DEEPSEEK_MODEL;

export interface GeneratedQuery {
	aiGenerated: true;
	title: string;
	kql: string;
	explanation: string;
	dialect: KqlDialect;
	tables: string[];
	assumptions: string[];
	supportingQueryIds: string[];
	model: DeepSeekModel;
	warning: "This query was generated by AI and was not executed or verified.";
}

export interface GenerationInput {
	request: SearchRequest;
	viewer: SearchViewer;
	targetDialect: KqlDialect;
	supportingResults: SearchResult[];
	privateProcessingAcknowledged: boolean;
	signal?: AbortSignal;
}

export interface GenerationPort {
	generateQuery(input: GenerationInput): Promise<GeneratedQuery>;
}

export interface GenerationBody {
	request: SearchRequest;
	targetDialect: KqlDialect | null;
	privateProcessingAcknowledged: boolean;
	turnstileToken?: string;
}
